#!/bin/bash

# This is the shell to install expected softwares on Ubuntu for java developer

echo "List all the softwares you can operate..."

echo ========================== System Tools Installation =================================

echo "1 --- openssh-server"
echo "2 --- Sysstat"
echo "3 --- sar"
echo "4 --- speedometer"
echo "5 --- nethogs"
echo "6 --- vnstat"
echo "7 --- ifstat"
echo "8 --- dstat"
echo "9 --- iftop"
echo "10 --- iptraf"
echo "11 --- tcptrack"
echo "12 --- pktstat"

echo ========================== Development Software Installation =================================
echo "1 --- vim"
echo "2 --- java"
echo "3 --- maven"
echo "4 --- docker CE"
echo "5 --- kubernetes"







